labels: ["status: needs-triage", "type: question"]
body:
  - type: textarea
    attributes:
      label: Coneixements previs
      description: |
        Quins coneixements previs existeixen en base al dubte? Si us plau, descriu quins coneixements previs existeixen en base al dubte.
        Per una millor comprensió, s'hauria d'incloure, mínimament, un coneixement previ...
      value: |
        - Primer coneixement previ...
        - Segon coneixement previ...
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Dubte
      description: Quin és el dubte que tens? Si us plau, descriu el dubte que tens.
      placeholder: |
        Dubte 1...?


        Si disposes de més d'un dubte relacionat amb el mateix tema, pots afegir-ne més.
        - Dubte 1...?
        - Dubte 2...?
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solució proposada
      description: Quina solució proposaries? Si us plau, descriu la solució que proposaries.
      placeholder: |
        Solució 1...


        Si disposes de més d'una solució, pots afegir-ne més.
        - Solució 1...
        - Solució 2...
        ...
    validations:
      required: true
