labels: ["status: needs-triage", "type: question"]
body:
  - type: textarea
    attributes:
      label: Coneixements previs
      description: Quins coneixements previs existeixen en base al dubte?
      value: |
        <!--
        Per favor, descriu quins coneixements previs existeixen en base al dubte.
        Per una millor comprensió, s'hauria d'incloure, mínimament, un coneixement previ.
        -->
        - Primer coneixement previ...
        - Segon coneixement previ...
        ...
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Dubte
      description: Quin és el dubte que tens?
      value: |
        <!--
        Per favor, descriu el dubte que tens.
        -->
        Dubte 1...?
        <!--
        Si disposes de més d'un dubte relacionat amb el mateix tema, pots afegir-ne més.
        - Dubte 1...?
        - Dubte 2...?
        ...
        -->
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solució proposada
      description: Quina solució proposaries?
      value: |
        <!--
        Per favor, descriu la solució que proposaries.
        -->
        Solució 1...
        <!--
        Si disposes de més d'una solució, pots afegir-ne més.
        - Solució 1...
        - Solució 2...
        ...
        -->
      render: markdown
    validations:
      required: true
